const users = [
  {
    name: 'miguel freeman',
    city: 'miami gardens',
    email: 'miguel.freeman@example.com',
    dob: '1990-04-07 13:55:50',
    nationality: 'US',
  },
  {
    name: 'minnie larson',
    city: 'edison',
    email: 'minnie.larson@example.com',
    dob: '1963-05-18 19:33:18',
    nationality: 'US',
  },
  {
    name: 'chiara lemoine',
    city: 'aclens',
    email: 'chiara.lemoine@example.com',
    dob: '1985-06-17 13:56:37',
    nationality: 'CH',
  },
  {
    name: 'chaiane gomes',
    city: 'nova iguaçu',
    email: 'chaiane.gomes@example.com',
    dob: '1979-10-24 03:58:38',
    nationality: 'BR',
  },
  {
    name: 'dave montgomery',
    city: 'gladstone',
    email: 'dave.montgomery@example.com',
    dob: '1964-07-08 16:28:47',
    nationality: 'AU',
  },
  {
    name: 'asta madsen',
    city: 'københavn n',
    email: 'asta.madsen@example.com',
    dob: '1969-10-01 02:39:01',
    nationality: 'DK',
  },
  {
    name: 'nathan roy',
    city: 'inwood',
    email: 'nathan.roy@example.com',
    dob: '1971-09-13 20:34:39',
    nationality: 'CA',
  },
  {
    name: 'clarisse lopez',
    city: 'strasbourg',
    email: 'clarisse.lopez@example.com',
    dob: '1967-10-11 11:57:33',
    nationality: 'FR',
  },
  {
    name: 'nicky evans',
    city: 'sheffield',
    email: 'nicky.evans@example.com',
    dob: '1963-11-11 12:15:19',
    nationality: 'GB',
  },
  {
    name: 'josse quaak',
    city: 'ommen',
    email: 'josse.quaak@example.com',
    dob: '1967-03-02 11:08:58',
    nationality: 'NL',
  },
  {
    name: 'henry moore',
    city: 'boise',
    email: 'henry.moore@example.com',
    dob: '1967-07-08 04:27:15',
    nationality: 'US',
  },
  {
    name: 'terri bennett',
    city: 'rockhampton',
    email: 'terri.bennett@example.com',
    dob: '1955-12-07 00:12:59',
    nationality: 'AU',
  },
  {
    name: 'veera toivonen',
    city: 'lapinlahti',
    email: 'veera.toivonen@example.com',
    dob: '1962-01-03 00:17:02',
    nationality: 'FI',
  },
  {
    name: 'anaëlle blanchard',
    city: 'vitry-sur-seine',
    email: 'anaëlle.blanchard@example.com',
    dob: '1950-08-06 22:40:14',
    nationality: 'FR',
  },
  {
    name: 'valentin carpentier',
    city: 'saint-denis',
    email: 'valentin.carpentier@example.com',
    dob: '1987-03-14 21:33:24',
    nationality: 'FR',
  },
  {
    name: 'carter ward',
    city: 'maitland',
    email: 'carter.ward@example.com',
    dob: '1963-10-05 07:20:15',
    nationality: 'AU',
  },
  {
    name: 'diana fowler',
    city: 'hereford',
    email: 'diana.fowler@example.com',
    dob: '1968-10-15 19:58:55',
    nationality: 'GB',
  },
  {
    name: 'tara mason',
    city: 'sunshine coast',
    email: 'tara.mason@example.com',
    dob: '1976-07-16 15:39:34',
    nationality: 'AU',
  },
  {
    name: 'kerttu pesola',
    city: 'iisalmi',
    email: 'kerttu.pesola@example.com',
    dob: '1986-01-26 04:56:31',
    nationality: 'FI',
  },
];

export default users.map((user, i) => ({ ...user, id: i + 1 }));
